# Generated by Django 3.2.6 on 2021-09-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_heart_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
    ]
